//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateNote
    {
        public int Id { get; set; }
        public int CandidateId { get; set; }
        public string Note { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
