//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyContactInformations = new HashSet<CompanyContactInformation>();
            this.Customers = new HashSet<Customer>();
            this.CompanyMailAddresses = new HashSet<CompanyMailAddress>();
        }
    
        public int Id { get; set; }
        public System.Guid GlobalEntityId { get; set; }
        public string Name { get; set; }
        public int CompanyTypeId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> RevenueSizeTypeId { get; set; }
        public Nullable<int> EmployeeSizeTypeId { get; set; }
        public Nullable<int> BillingFrequencyTypeId { get; set; }
        public Nullable<int> BillingMethodTypeId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> MPLOY_OrganizationId { get; set; }
        public Nullable<int> MPLOY_IdUser { get; set; }
    
        public virtual ICollection<CompanyContactInformation> CompanyContactInformations { get; set; }
        public virtual GlobalEntity GlobalEntity { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<CompanyMailAddress> CompanyMailAddresses { get; set; }
    }
}
