//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInformationType
    {
        public ContactInformationType()
        {
            this.PersonContactInformations = new HashSet<PersonContactInformation>();
            this.CompanyContactInformations = new HashSet<CompanyContactInformation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string InfoFormat { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual ICollection<PersonContactInformation> PersonContactInformations { get; set; }
        public virtual ICollection<CompanyContactInformation> CompanyContactInformations { get; set; }
    }
}
