//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class GetHiringActivityAssociation_Result1
    {
        public Nullable<int> @int { get; set; }
        public Nullable<int> int1 { get; set; }
    }
}
