//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalEntity
    {
        public GlobalEntity()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Customers = new HashSet<Customer>();
            this.Requirements = new HashSet<Requirement>();
            this.Companies = new HashSet<Company>();
        }
    
        public System.Guid GlobalEntityId { get; set; }
        public int EntityTypeId { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual ICollection<Candidate> Candidates { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
    }
}
