//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class InsertPersonSkill_Result1
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int SkillId { get; set; }
        public Nullable<int> ExpertiseLevelTypeId { get; set; }
        public Nullable<int> ExperienceInMonths { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    }
}
