//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class InsertCustomer_Result2
    {
        public int Id { get; set; }
        public System.Guid GlobalEntityId { get; set; }
        public int CompanyId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> SourceTypeId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> MPLOY_OrganizationId { get; set; }
    }
}
