//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailingAddress
    {
        public MailingAddress()
        {
            this.CompanyMailAddresses = new HashSet<CompanyMailAddress>();
            this.PersonMailAddresses = new HashSet<PersonMailAddress>();
        }
    
        public int Id { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Stop { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual ICollection<CompanyMailAddress> CompanyMailAddresses { get; set; }
        public virtual ICollection<PersonMailAddress> PersonMailAddresses { get; set; }
    }
}
