//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class ReadPerson_Result5
    {
        public Nullable<int> idcontact { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> idorganization { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string email { get; set; }
        public string Line1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Title { get; set; }
        public string Gender { get; set; }
        public string iduserowner_as_iduser { get; set; }
        public string Status { get; set; }
        public string Source { get; set; }
        public string handle0text { get; set; }
        public string handle0type { get; set; }
        public string handle1text { get; set; }
        public string handle1type { get; set; }
        public string handle2text { get; set; }
        public string handle2type { get; set; }
        public string handle3text { get; set; }
        public string handle3type { get; set; }
        public string Notes { get; set; }
        public string ResumeText { get; set; }
        public string xdata { get; set; }
    }
}
