//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class ReadOrganization_Result4
    {
        public int idOrganization { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string URL { get; set; }
        public System.DateTime Created { get; set; }
        public int idOrganizationType { get; set; }
        public string InternalNote { get; set; }
        public string ExternalNote { get; set; }
        public Nullable<int> idUserOwner { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> idbranch { get; set; }
        public string Country { get; set; }
    }
}
