//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class ReadPerson_Result4
    {
        public Nullable<int> Copy_of_idcontact { get; set; }
        public Nullable<System.DateTime> Copy_of_Created_Date { get; set; }
        public Nullable<int> Copy_of_idorganization { get; set; }
        public string Copy_of__lastname { get; set; }
        public string Copy_of_middlename { get; set; }
        public string Copy_of_firstname { get; set; }
        public string Copy_of_email { get; set; }
        public string Copy_of_address { get; set; }
        public string Copy_of_city { get; set; }
        public string Copy_of_state { get; set; }
        public string Copy_of_zip { get; set; }
        public string Copy_of_title { get; set; }
        public string Copy_of_gender { get; set; }
        public string Copy_of_iduserowner_as_iduser { get; set; }
        public string Copy_of_status { get; set; }
        public string Copy_of_source { get; set; }
        public string Copy_of_handle0text { get; set; }
        public string Copy_of__handle0type { get; set; }
        public string Copy_of_handle1text { get; set; }
        public string Copy_of__handle1type { get; set; }
        public string Copy_of__handle2text { get; set; }
        public string Copy_of__handle2type { get; set; }
        public string Copy_of__handle3text { get; set; }
        public string Copy_of__handle3type { get; set; }
        public string Copy_of_notes { get; set; }
        public string Copy_of_resumetext { get; set; }
        public string Copy_of_xdata { get; set; }
    }
}
