//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    
    public partial class ReadOrganization_Result1
    {
        public string idorganization { get; set; }
        public string Organization { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Url { get; set; }
        public string InternalNote { get; set; }
        public string ExternalNote { get; set; }
        public string OrganizationType { get; set; }
        public string iduserownerAsIduser { get; set; }
    }
}
