//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesRecruitingActivityLog
    {
        public int Id { get; set; }
        public int SalesRecruitingWorkflowId { get; set; }
        public System.Guid GlobalEntityId { get; set; }
        public string ActivityNote { get; set; }
        public string ActivityOutcome { get; set; }
        public System.DateTime ActivityTimestamp { get; set; }
        public Nullable<int> PayRate { get; set; }
        public Nullable<int> BillRate { get; set; }
        public Nullable<System.DateTime> ScheduledDateTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int CreatedById { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> MPLOY_ContactId { get; set; }
        public Nullable<int> MPLOY_UserId { get; set; }
    
        public virtual GlobalEntity GlobalEntity { get; set; }
    }
}
